### ISSUE TITLE
Size of export file is to small, some vertices and edges are missing.

### ISSUE THREAD

**Issue by thatUserjm** [PSEProgrammgraphen/GraphVonAnsicht#46]
File: `BigControl.pdg.graphml`
Graph: `java.io.PrintStream.print(I)V`
After importing and adjusting of the scaling that the whole graph is visible and exporting, the sg-file looks like: (commit hash ff7a1c862ecdb13aa8d4187bba3fde80f9a0c60e)
![export view size fehler](https://cloud.githubusercontent.com/assets/19251666/17745401/eda8d99c-64ab-11e6-8c47-9fc1d5d7a267.PNG)

but in the graphviewer the graph looks like:
![export view size soll](https://cloud.githubusercontent.com/assets/19251666/17745421/fb475a38-64ab-11e6-93d3-40472749e5da.PNG)

**Comment by JonasFehrenbach** [comment]
It seems like some svg viewer have inconsistences with handling the size of a svg file.
I tried out chrome, inkscape and adobe illustrator, which all displayed the file correctly.
But i got the same result with Internet Explorer 11.
Which svg viewer did you use @thatUserjm ?

Possible solutions would be:
1. set a fixed size to every exported svg file like 5000x5000 and hoping that no file will be exported which is larger. The problem is that small graphs will also have the size of 5000x5000. (worst solution)
2. Getting the whole size of the graph from the graphviewer to adjust the file of the svg. (is this possible @Nicolas-Boltz? )
3. Don't support Internet Explorer :)

**Comment by JonasFehrenbach** [comment]
I decided to let the svg exporter calculate the max coordinates of all shapes to set height and width.
